### ISSUE TITLE
Feature Idea: "Flashlight"

### ISSUE THREAD

**Issue by mycrEEpy** [Ixrec/OuterWildsArchipelagoRandomizer#31]
Just thought about the idea to add the flashlight to the item pool as `progression`.
All locations which are dark (underground caves like sunless city, zero-g-cave etc.) would require the flashlight to be in logic.
From my knowledge entering the stranger would also require the flashlight (have not played the DLC much).
This should maybe also be added to `early_key_item` if implemented.

**Comment by Ixrec** [comment]
A flashlight item has been suggested in the past (so much it's kind of a meme in the AP Discord thread) but never implemented because

![image](https://github.com/user-attachments/assets/bda60b58-51f6-4b00-9f63-4861babab6fc)

After ten months and dozens of releases, ^this never changed much. But we can spell out the argument in much more detail now that it's been fully explored and settled, so:
- The Zero-G cave is almost fully covered in other light sources after that initial left turn
- Sunless City is usually accessed through the not-that-dark shortcut by the gravity cannon anyway
- Flashlight is used to make quantum objects move around, but alternative light sources like your jetpack or the Scout are too easy to be out of logic, yet also annoying enough that we'd rather not require them, and probably some players wouldn't realize those alternatives exist...
- The only dark-enough locations left would be I think the trip to HEL, maybe Coleus' Cave, maybe Cave Shard itself? Which are also all pretty easy to do with jetpack lighting, and none of those have an alternative access using any non-flashlight item.
- Plus, lots of places are just dark enough that lack of flashlight would be annoying, yet nowhere near dark enough that it would make sense for flashlight to be a logical requirement.

So from a randomizer design perspective, there's just not much potential value here... in the base game. For a long time "the flashlight question" was one I was putting off until Echoes of the Eye DLC integration, because we all knew the most compelling flashlight blockers were all in the Stranger.

To make a very long design process short, I ended up concluding that a "Stranger Light Modulator" item for controlling owlk rafts, doors and elevators, with a special exception for the airlocks, and the laboratory doors being controlled instead by "Breach Override Codes", is a better overall design than any of the options that involved taking away the entire flashlight. There were lots of interrelated reasons for that, but the biggest one relevant to this topic is that it allows for several different ways of gradually gaining access to more of the Stranger and DW, while "just" itemifying the flashlight as-is would have made the flashlight a hard requirement to do anything in the DLC yet also instantly unlock almost the entire non-DW half of the DLC.

I guess the tl;dr is either "We already did, the AP item part is just called 'Stranger Light Modulator'" or "We decided not to because it'd be annoying in a lot of places and do very little to block locations/change item placements/make players take unusual routes/etc".
