### ISSUE TITLE
Softlocked in midgame/start of endgame

### ISSUE THREAD

**Issue by Chara-heartiens** [Ixrec/OuterWildsArchipelagoRandomizer#41]
Pretty simple,I only have a few things left to do but for all of them I just dont have the tools in game to do so.

For exemple one I'm supposed to be able to do is scan gabro's signal,which I didnt unlock,and scan the deep satelite signal,which  I didnt unlock either.

Tried to unlock myself by going to the sunstation without the teleporter since I didnt unlock that yet and I got the entengelment rule! which then gave me a boost upgrade to rip lmao

I then tried to teleport myself to the vessel as I dont have the thruster mufflers or the ejection sit to try to pass throught,and it didnt count it even if I try to leave or comeback ect

I'm assuming that everything unlockable about the stranger is in there (didnt got time to explore it that much yet) and I'm also assuming that there's nothing for the base game in there,if I'm wrong then I might not be softlocked but if I'm right,even the cheats cant get me access to all the frequencies and stuff like that so that's a rip

Pretty neat mode and I'll probably give it a second try later on,the random orbits are really sick.

Something else I'll like to report too is that the game considered I shouldnt be able to access feldspar's camp,which I did with just his outer wild signal so idk if that's normal,I lost a lot of time on it because I assumed I had to find something else but ho well

**Comment by Ixrec** [comment]
There's way too little information here to investigate. For example, does the tracker in the ship log show any locations as green? Are you playing a multiworld with any other players that you might be waiting on? Can I see the .yaml and the room link? etc, etc.

The only part I can answer as-is is the last paragraph: That's all intended. Logically, all of Dark Bramble requires the "Silent Running Mode" item so you can sneak past the anglerfish like you do in vanilla (keep in mind that randomized DB layout might require you to sneak past fish at any time). But this is one of the places where it's often relatively easy to "go out of logic" and explore the fish-free or low-fish parts of DB without SRM. That's an intentional design trade-off.
